### Import Required Packages and Set Options

In [432]:
import os
import sys

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import jax.numpy as jnp
from jax import grad, jit, vmap

from datetime import datetime
from pandas.api.types import CategoricalDtype
from scipy.sparse import csr_matrix

from sklearn.datasets import load_boston
from sklearn.base import BaseEstimator, TransformerMixin

jnp.set_printoptions(precision=4, suppress=True)

In [433]:
REPO_ROOT = "/Users/ericlundquist/Repos/rankfm"

### Load Example Data

In [512]:
boston = load_boston()
features = boston.data
target = boston.target

# convert to z-scores for numerical stability and add constant column
features = (features - features.mean(axis=0)) / features.std(axis=0)
features = jnp.hstack([jnp.ones([features.shape[0], 1]), features])

# transform the target to a binary value
target = jnp.where(target > target.mean(), 1, 0)

coeffs = ['CONS'] + list(boston.feature_names)
print(" ".join(coeffs))
print(features.shape)
print(target.shape)

CONS CRIM ZN INDUS CHAS NOX RM AGE DIS RAD TAX PTRATIO B LSTAT
(506, 14)
(506,)


In [437]:
print(features.mean(axis=0))
print(features.std(axis=0))
print(target.mean())

[ 1.  0.  0. -0. -0. -0.  0.  0.  0. -0. -0.  0.  0. -0.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
0.41304347


### Train a Logistic Regression Model with Mini-Batch SGD Gradient Updates 

In [681]:
def mini_batch_train(inputs, target, initial_weights, batch_size=10, lr=0.1, epochs=10):
    """learn model weights using SGD"""
    
    def sigmoid(x):
        return 1 / (1 + jnp.exp(-x))

    def predict_proba(weights, inputs):
        return sigmoid(jnp.dot(inputs, weights))

    def loss_value(weights, inputs, target):
        predictions = predict_proba(weights, inputs)
        loss = -jnp.mean((target * jnp.log(predictions)) + ((1 - target) * jnp.log(1 - predictions)))
        return loss
    
    def create_batches(inputs, target, batch_size):
        n_batches = np.round(inputs.shape[0] / batch_size)

        batch_inputs = np.array_split(inputs, n_batches)
        batch_target = np.array_split(target, n_batches)
        return list(zip(batch_inputs, batch_target))
    
    # auto-grad the loss function
    loss_grad = grad(loss_value)
    
    @jit
    def train_batch(batches, weights):
        for (b_input, b_target) in batches:
            weights = weights - (lr * loss_grad(weights, b_input, b_target))
        return weights
    
    # initialize the weights 
    weights = initial_weights
    print("initial loss: {}".format(round(loss_value(weights, inputs, target), 2)))
    
    # train weights using gradient descent
    for i in range(epochs):
        batches = create_batches(inputs, target, batch_size)
        weights = train_batch(batches, weights)
        print("epoch: {} loss: {}".format(i, loss_value(weights, inputs, target)))
            
    return weights
        

#### Full Batches

In [682]:
initial_weights = jnp.zeros(inputs.shape[1])
final_weights = mini_batch_train(features, target, initial_weights, batch_size=len(target), lr=0.1, epochs=10)

initial loss: 0.6899999976158142
epoch: 0 loss: 0.6455785632133484
epoch: 1 loss: 0.6100115180015564
epoch: 2 loss: 0.5829105377197266
epoch: 3 loss: 0.5617798566818237
epoch: 4 loss: 0.5449056029319763
epoch: 5 loss: 0.5311164855957031
epoch: 6 loss: 0.5196055173873901
epoch: 7 loss: 0.5098092555999756
epoch: 8 loss: 0.5013279914855957
epoch: 9 loss: 0.4938735067844391


#### Mini-Batches

In [683]:
initial_weights = jnp.zeros(inputs.shape[1])
final_weights = mini_batch_train(features, target, initial_weights, batch_size=10, lr=0.1, epochs=10)

initial loss: 0.6899999976158142
epoch: 0 loss: 0.39493054151535034
epoch: 1 loss: 0.35050806403160095
epoch: 2 loss: 0.3332710564136505
epoch: 3 loss: 0.323830783367157
epoch: 4 loss: 0.3177531063556671
epoch: 5 loss: 0.3134887218475342
epoch: 6 loss: 0.3103281557559967
epoch: 7 loss: 0.3078918159008026
epoch: 8 loss: 0.30595651268959045
epoch: 9 loss: 0.30438217520713806


#### Single-Sample SGD

In [671]:
initial_weights = jnp.zeros(inputs.shape[1])
final_weights = mini_batch_train(features, target, initial_weights, batch_size=1, lr=0.1, epochs=10)

initial loss: 0.6899999976158142
epoch: 0 loss: 0.35765910148620605
epoch: 1 loss: 0.3244864344596863
epoch: 2 loss: 0.3173229694366455
epoch: 3 loss: 0.3147937059402466
epoch: 4 loss: 0.31364718079566956
epoch: 5 loss: 0.31306958198547363
epoch: 6 loss: 0.31278374791145325
epoch: 7 loss: 0.3126581013202667
epoch: 8 loss: 0.31262409687042236
epoch: 9 loss: 0.31264904141426086


### Mess Around with VMAP()

In [632]:
weights = np.array([1, 2, 3, 4])
matrix = np.arange(16).reshape((4, 4))
batches = np.split(matrix, 4)

In [633]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [634]:
batches

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [675]:
def running_sum(batches, weights, cursum):
    for batch in batches:
        cursum += jnp.dot(batch, weights)
    return cursum


In [676]:
%%timeit

cursum = 1000
running_sum(batches, weights, cursum)

3.33 ms ± 119 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [677]:
np.sum(np.dot(matrix, weights))

320

In [678]:
vmap_running_sum = vmap(running_sum, in_axes=(0, None, None))

In [679]:
%%timeit

cursum = 1000
vmap_running_sum(batches, weights, cursum)

7.37 ms ± 370 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
